### ISSUE TITLE
EPIC: inloggen Yivi voor bedrijven op ACCP mogelijk maken mijn-nijmegen

### ISSUE THREAD

**Issue by wvdeeckhout** [GemeenteNijmegen/mijn-nijmegen#1041]
Het is voor inwoners mogelijk om met Yivi in te loggen op Mijn Nijmegen. Deze epic is om het mogelijk te maken voor ondernemers om in te loggen met Yivi op de acceptatieomgeving van Mijn Nijmegen. De leerpunten hieruit kunnen we gebruiken om Yivi voor bedrijven in te richten op onze formulierenomgeving.

```[tasklist]
### Tasks
- [ ] https://github.com/GemeenteNijmegen/mijn-nijmegen/issues/1071
- [ ] https://github.com/GemeenteNijmegen/mijn-nijmegen/issues/1072
- [ ] https://github.com/GemeenteNijmegen/mijn-nijmegen/issues/1073
```
