### ISSUE TITLE
Linkjes naar andere portalen vanuit Mijn Nijmegen ontwerpen

### ISSUE THREAD

**Issue by MariannevanLierop** [GemeenteNijmegen/mijn-nijmegen#1046]
Componenten maken vanuit design system project. Makkelijkste oplossing voor nu: op homepage tegels (oid) naar de belangrijkste portalen:

- Belastingen: https://belastingen.nijmegen.nl/view/LOGIN
- Mijn Wijkplan: https://nijmegen.mijnwijkplan.nl/
- Parkeren: https://parkeerproducten.nijmegen.nl/Account/LogOn?ReturnUrl=%2f
- Meld&Herstel: https://nijmegen.jouw-omgeving.nl/burgermelding

Toekomstmuziek: een link + sso inlog dus dat je als inwoner meteen ingelogd op de juiste plek zit. En nóg idealiter zit het allemaal geïntegreerd in Mijn Nijmegen zelf. Maar als we klein beginnen: linkjes naar de portalen.
```[tasklist]
### Tasks
- [x] Bepalen welke portalen --> Myriam selectie maken
- [x] Ontwerp maken (4 linkjes ongeveer) --> Vladimir
- [x] Content check --> Myriam
- [x] Ticket aanmaken comp biblio bord
- [ ] Checken bij Wendy/Joost Kamphuis of ze akkoord zijn --> Marianne
- [ ] Component maken via comp biblio project
```

**Comment by joostvanderborg** [comment]
Ik kan het ontwerp niet vinden, @iamskip waar is dit te zien?

**Comment by vladimirdacosta** [comment]
@joostvanderborg In het overzicht, onderaan de pagina https://www.figma.com/design/MScSuv6Z23Z0LFfCWXAxdY/MijnNijmegen?node-id=1581%3A6129&t=p5L2PPXBlwD0bfCf-1
