### ISSUE TITLE
EPIC: Statusinformatie uit VrijBRP tonen (deel C)

### ISSUE THREAD

**Issue by wvdeeckhout** [GemeenteNijmegen/mijn-nijmegen#1115]
## Epic
Om te voldoen aan een transparante overheid, de Nijmegenaar inzicht te geven in de status van zijn lopende zaken bij de gemeente en meer regie te geven op zijn eigen processen, is het belangrijk dat proactief beschikbaar komt op MijnNijmegen. Dit betekent dat statusinformatie uit VrijBRP getoond gaan worden op MijnNijmegen.

**Intake:**
 https://irvn.sharepoint.com/sites/NijmegenAfstemmingsoverleg/Lists/Intakes/DispForm.aspx?ID=774&Source=https%3A%2F%2Firvn%2Esharepoint%2Ecom%2Fsites%2FNijmegenAfstemmingsoverleg%2FLists%2FIntakes%2FMijn%2520Intakes%2Easpx&ContentTypeId=0x01008DB40EF2E2C16F47964C85F514CE4F3A

## Status
We implementeren eerst statusinfo met VIP. Lopen in projecten VNG mee, VNG is ook bezig met VrijBRP om ZGW-api's te gaan ondersteunen. Wij wachten even af wat daar gebeurt.

## Issues
```[tasklist]
- [x] GemeenteNijmegen/mijn-nijmegen#311
- [x] https://github.com/GemeenteNijmegen/devops/issues/242
- [x] GemeenteNijmegen/mijn-nijmegen#390
- [x] wacht op uitkomen epic GemeenteNijmegen/mijn-zaken#27
- [ ] https://github.com/GemeenteNijmegen/mijn-nijmegen/issues/1253
- [ ] https://github.com/GemeenteNijmegen/mijn-nijmegen/issues/1258
- [ ] https://github.com/GemeenteNijmegen/mijn-nijmegen/issues/1259
```

**Comment by wvdeeckhout** [comment]
inplannen overleg met Procura

**Comment by joostvanderborg** [comment]
Resultaat epic beter omschrijven (@me) + status (VNG die hieraan trekt)

**Comment by joostvanderborg** [comment]
![Image](https://github.com/user-attachments/assets/c7d01b41-6d20-48a9-9f3f-968464e213b8)

**Comment by wvdeeckhout** [comment]
De hackathon is geweest, het is los van elkaar gelukt om de status te tonen op Mijn Nijmegen, maar helaas niet in zijn geheel. Deze epic wordt gesloten. We gaan de werkzaamheden evalueren en bekijken wat er verder gedaan moet worden. Er wordt dan een nieuwe epic aangemaakt.
