### ISSUE TITLE
EPIC: Klachten JZ statusinformatie tonen (deel B)

### ISSUE THREAD

**Issue by wvdeeckhout** [GemeenteNijmegen/mijn-nijmegen#1118]
**EPIC omschrijving**
De statusinformatie van JZ zit in dezelfde bron als de statusinformatie van VIP. Dit is van dezelfde leverancier Woweb. De statusinformatie VIP wordt straks aangeboden in Mijn Nijmegen. In de JZ4all applicatie staan klachten en bezwaren opgenomen. Deze epic gaat over het tonen van statusinformatie van klachten op Mijn Nijmegen. **NB: Tonen van bezwaren dus nog niet. Filteren op zaaktype?**

fasering voor klachten:

Fasering onderdeel klachten JZ4all
Fase 1 Tonen van statusinformatie op Mijn Nijmegen, dat kan er als volgt uitzien:
 
Waarbij zelf te bepalen is:
1.	Welke statussen wil je getoond hebben
2.	Bij verdaging de einddatum aanpassen
3.	Ingediende klacht/bezwaar tonen bij de status
 
Fase 2 Toevoegen Behandelaar klachten           
Of Coördinator klachten
Fase 3 Notificeren bij een statuswijziging via een e-mail en/of een sms naar de indiener
 
Fase 4 Taak toewijzen aan een inwoner, bijvoorbeeld vergeten een bijlage bij te sturen.
 
Hierbij kan ook een notificatie verstuurd worden naar de indiener.
 
Fase 3 en 4 zijn om te wisselen.

```[tasklist]
### Issues
- [ ] https://github.com/GemeenteNijmegen/mijn-zaken/issues/74
- [ ] https://github.com/GemeenteNijmegen/devops/issues/617
- [x] JZ bezwaren uitfilteren voor Mijn Nijmegen
- [ ] https://github.com/GemeenteNijmegen/mijn-nijmegen/issues/1122
```

**Comment by marnixdessing** [comment]
Begin december neemt Joost contact op met JZ

**Comment by wvdeeckhout** [comment]
Reactie van de stafmedewerker:
Of MijnNijmegen interessant is voor klanten van JZ (die bezwaar of beroep hebben aangetekend) valt te bezien. Er zijn weinig opties te delen mbt statusinformatie:  
a.       een bezwaar is ontvangen; een zitting wordt/ is gepland
of
b.       een bezwaar is ontvangen; niet ontvankelijk; er wordt geen zitting gepland.
Ik heb ook begrepen dat klanten hierover per brief worden geïnformeerd.
Of er op termijn toch behoefte is aan te sluiten op MijnNijmegen kun je het best direct opnemen met de nieuwe manager JZ
