### ISSUE TITLE
EPIC: TTL submission storage voor opslag

### ISSUE THREAD

**Issue by wvdeeckhout** [GemeenteNijmegen/mijn-nijmegen#1165]
Datum voor verwijderen na een jaar nadert. Hiervoor is het nodig om te weten welke producten erin staan en wat de datum is, zodat Wendy hiermee met de afdeling in gesprek kan. 

Issues worden uitgewerkt door Wieteke en Marnix.
```[tasklist]
### Tasks
- [ ] https://github.com/GemeenteNijmegen/mijn-nijmegen/issues/1166
- [ ] https://github.com/GemeenteNijmegen/mijn-nijmegen/issues/1167
- [ ] https://github.com/GemeenteNijmegen/mijn-nijmegen/issues/1168
- [ ] [TTL Submission] S3 Bucket staat nu op 2 jaar
- [ ] [TTL Submission] DynamoDB heeft geen TTL
- [ ] [TTL Submission] Wat willen we hier nou uiteindelijk mee? Eindconclusie
```

**Comment by wvdeeckhout** [comment]
@marnixdessing en @WietekeNijmegen deze kan gesloten worden denk ik? We hebben het nu ingericht dat na 2 jaar de documenten verwijderd worden. Als jullie het ermee eens zijn, dan graag sluiten.
