### ISSUE TITLE
EPIC: Taken Woweb naar productie

### ISSUE THREAD

**Issue by joostvanderborg** [GemeenteNijmegen/mijn-nijmegen#1301]
We willen taken gaan gebruiken voor aanvullingsverzoeken bij VIP.

Het takenpatroon is geïmplementeerd in de hackathon. Om dit productiewaardig te krijgen is aan onze kant nog wat werk nodig. Dit is productiewaardig als:
- Taken vanuit VIP opgepakt kunnen worden
- Deze weergegeven worden in Mijn Nijmegen
- Bijlages in de taken getoond kunnen worden in Mijn Nijmegen.

Om in productie te gaan zijn notificaties ook nodig. Dit wordt in GemeenteNijmegen/mijn-services#57 getracked en is buiten scope voor deze epic.

```[tasklist]
### Woweb Taken
- [ ] https://github.com/GemeenteNijmegen/mijn-nijmegen/issues/1302
- [ ] https://github.com/GemeenteNijmegen/mijn-nijmegen/issues/1304
- [ ] https://github.com/GemeenteNijmegen/mijn-nijmegen/issues/1305
- [ ] https://github.com/GemeenteNijmegen/mijn-nijmegen/issues/1348
```
