### ISSUE TITLE
EPIC: Als Nijmegenaar wil ik mijn Gegevens inzien in een MijnNijmegen portaal

### ISSUE THREAD

**Issue by BramWithaar** [GemeenteNijmegen/mijn-nijmegen#158]
Dit betreft een burgerportaal en geen integraal klantbeeld voor de medewerkers. Voor de inwoner persoonsgebonden informatie die de gemeente in bezit heeft, inzichtelijk maken. Statusinformatie van een zaak inzien voor de inwoner.

**Comment by BramWithaar** [comment]
- [x] MVP is persoonsgegevens inzien (BRP)
- [ ] Uploaden documenten
- [ ] Uitbreiden met informatie uit taakspecifieke applicaties
- [ ] Uitbreiden met satelliet websites
- [ ] Uitbreiden met tips
- [ ] Betalingen kunnen doen
- [ ] Aanvragen in kunnen dienen

**Comment by BramWithaar** [comment]
@wvdeeckhout Moet dit een epic blijven, of issues/epics maken als er daadwerkelijk vraag komt vanuit publiekszaken/dienstverlening?

**Comment by wvdeeckhout** [comment]
Ik sluit deze epic. Mijn Nijmegen is in productie. Nieuwe wensen komen in een nieuwe epic.
