### ISSUE TITLE
EPIC: verbeteren application monitoring mijn-nijmegen

### ISSUE THREAD

**Issue by MartijnvDijk** [GemeenteNijmegen/mijn-nijmegen#212]
- [x] https://github.com/GemeenteNijmegen/mijn-nijmegen/issues/215
- [x] Onderzoek naar gebruik x-ray in ander projecten
- [x] https://github.com/GemeenteNijmegen/cdk-repository-template/issues/5

**Comment by wvdeeckhout** [comment]
@MartijnvDijk wil je deze epic aanvullen met doel/omschrijving? of kan deze komen te vervallen?

**Comment by MartijnvDijk** [comment]
@wvdeeckhout deze wil ik laten staan. Ik zal de prioriteit naar laag zetten en de omschrijving aanvullen.

**Comment by MartijnvDijk** [comment]
Niet meer relevant
