### ISSUE TITLE
EPIC: MijnNijmegen - Statusinformatie tonen

### ISSUE THREAD

**Issue by wvdeeckhout** [GemeenteNijmegen/mijn-nijmegen#287]
Om te voldoen aan een transparante overheid, de Nijmegenaar inzicht te geven in de status van zijn lopende zaken bij de gemeente en meer regie te geven op zijn eigen processen, is het belangrijk dat proactief beschikbaar komt op MijnNijmegen. Dit betekent dat statusinformatie uit taakspecifieke applicaties getoond gaan worden op MijnNijmegen.

Team dienstverlening zorgt voor de interne communicatie; de data moet op orde zijn en de proceseigenaar geeft aan welke informatie getoond gaat worden. Samen met Team online zorgen ze ervoor dat de Nijmegenaar hierin betrokken wordt en erbij betrokken wordt.

Op de planning voor 2023 staat:

- [ ] de status van een proces in VrijBRP (Procura) tonen op MijnNijmegen via MijnZaken. Dit samen met de VNG-R in een pilot MijnZaken.
- [ ] de status van zaken in VIP (Woweb) tonen op MijnNijmegen
- [ ] technisch onderzoek naar tonen statusinformatie uit andere applicaties die geen portaal hebben waar dit in staat
- [ ] technisch onderzoek naar doorlinken vanuit MijnNijmegen naar statusinformatie in een portaal die dit wel toont. Dit is afhankelijk van de klantreis: wat wil de Nijmegenaar hierin.

**Comment by wvdeeckhout** [comment]
inplannen overleg met Procura

**Comment by joostvanderborg** [comment]
Resultaat epic beter omschrijven (@me)
