### ISSUE TITLE
PROJECT 2025-2: SSO een aanvraag in OpenForms in kunnen dienen vanuit MijnNijmegen

### ISSUE THREAD

**Issue by wvdeeckhout** [GemeenteNijmegen/mijn-nijmegen#288]
**1. Epic omschrijving**
Het technisch mogelijk maken om in het MijnNijmegen portaal aanvragen in te kunnen dienen, zonder nog een keer jezelf te hoeven identificeren (SSO). Bij het invullen van het formulier is dat wat bekend is al reeds gevuld.

-aanvraag in kunnen dienen zonder nog een keer te hoeven identificeren
-formulieren tussentijds op kunnen slaan en vanuit MijnNijmegen daar later weer verder mee kunnen gaan
-formulieren zijn met de informatie die we al weten vooringevuld
-bij vragen kan "direct hulp bij invullen" ingediend worden; denk daarbij aan chatten met een medewerker, bellen of videobellen
-onderzoeken of we vanuit MijnNijmegen linken naar formulieren in andere portalen met SSO (belasting- en parkeerportaal hebben hun eigen formulieren) of dat we deze aanbieden in MijnNijmegen.

**2. Issues**
nader te bepalen
```[tasklist]
### Tasks
- [ ] https://github.com/GemeenteNijmegen/mijn-nijmegen/issues/783
- [ ] https://github.com/GemeenteNijmegen/mijn-nijmegen/issues/790
- [ ] ACCP: zelf een backchannel logout realiseren
- [ ] ACCP: aanvragen SSO op ACCP bij logius
- [ ] Testen SSO ACCP
```

tekst andere epic: 
Om te voorkomen dat bij wisselen tussen Mijn Nijmegen en de webformulieren 2x digid-login gedaan moet worden, evalueren of de signicat single sign-on geschikt is:

Todo:

checken of keep alive bij signicat door your request geïmplementeerd is
testen wat gebeurt als we (in accp) single sign-on aanzetten: Werkt login Mijn Nijmegen nog, doen webformulieren wat verwacht is?
Go/no-go aanzetten in productie

**Comment by wvdeeckhout** [comment]
Dit project wordt gesloten, Logius ondersteund geen SSO meer.
