### ISSUE TITLE
EPIC: inloggen voor bedrijven en instellingen met eHerkenning

### ISSUE THREAD

**Issue by wvdeeckhout** [GemeenteNijmegen/mijn-nijmegen#408]
**1. Epic**
Mogelijk maken om met eHerkenning in te loggen op MijnNijmegen. Omdat dit in eerste instantie voor VIP-producten van belang is, moeten we Khiem hierbij betrekken. Joost pakt dit op.

Khiem betrekken voor VIP producten (Joost)
aangeven bij team dienstverlening (Wendy)
communicatie bij productiegang ivm beperkte producten (Wendy team online, Joost in MijnNijmegen zelf?)

**2. Issues**
```[tasklist]
- [ ] https://github.com/GemeenteNijmegen/mijn-nijmegen/issues/563
- [ ] https://github.com/GemeenteNijmegen/mijn-nijmegen/issues/837
- [ ] https://github.com/GemeenteNijmegen/mijn-nijmegen/issues/843
- [ ] https://github.com/GemeenteNijmegen/mijn-nijmegen/issues/849
- [ ] https://github.com/GemeenteNijmegen/mijn-nijmegen/issues/892
```
```[tasklist]
### Mijn zaken voorbereiden op eherkenning-logins
- [ ] https://github.com/GemeenteNijmegen/mijn-nijmegen/issues/857
- [ ] https://github.com/GemeenteNijmegen/mijn-nijmegen/issues/858
- [ ] https://github.com/GemeenteNijmegen/mijn-nijmegen/issues/859
```
