### ISSUE TITLE
EPIC: Online aanvragen (bestanden) weergeven in Mijn Nijmegen

### ISSUE THREAD

**Issue by wvdeeckhout** [GemeenteNijmegen/mijn-nijmegen#581]
**EPIC:**
het tonen van de online aanvragen in Mijn Nijmegen.

```[tasklist]
### Issues:
- [ ] https://github.com/GemeenteNijmegen/mijn-nijmegen/issues/777
- [x] KCC informeren voordat het in productie gezet wordt
- [ ] https://github.com/GemeenteNijmegen/mijn-nijmegen/issues/690
- [ ] https://github.com/GemeenteNijmegen/webformulieren-submissionstorage/issues/34
- [ ] https://github.com/GemeenteNijmegen/mijn-nijmegen/issues/925
- [ ] https://github.com/GemeenteNijmegen/webformulieren-submissionstorage/issues/35
- [ ] https://github.com/GemeenteNijmegen/mijn-nijmegen/issues/889
- [ ] https://github.com/GemeenteNijmegen/mijn-nijmegen/issues/927
- [ ] https://github.com/GemeenteNijmegen/mijn-nijmegen/issues/929
- [ ] https://github.com/GemeenteNijmegen/mijn-nijmegen/issues/890
- [ ] https://github.com/GemeenteNijmegen/mijn-nijmegen/issues/928
```
```[tasklist]
### DoD
- [x] de inzendingen worden getoond in Mijn Nijmegen
```

```[tasklist]
### Productiegang
- [ ] https://github.com/GemeenteNijmegen/mijn-zaken/issues/412
- [ ] https://github.com/GemeenteNijmegen/mijn-nijmegen/issues/971
- [ ] https://github.com/GemeenteNijmegen/mijn-nijmegen/issues/972
- [ ] https://github.com/GemeenteNijmegen/webformulieren/issues/1422
- [ ] https://github.com/GemeenteNijmegen/mijn-nijmegen/issues/974
```
