### ISSUE TITLE
EPIC: navigatie verbeteren

### ISSUE THREAD

**Issue by joostvanderborg** [GemeenteNijmegen/mijn-nijmegen#587]
## Omschrijving
Omdat Mijn Nijmegen meer content krijgt, voldoet de navigatie niet meer. Verbeteringen zijn nodig:

```[tasklist]
### Issues
- [ ] https://github.com/GemeenteNijmegen/mijn-nijmegen/issues/595
- [ ] https://github.com/GemeenteNijmegen/mijn-nijmegen/issues/588
- [ ] https://github.com/GemeenteNijmegen/mijn-nijmegen/issues/758
- [ ] https://github.com/GemeenteNijmegen/mijn-nijmegen/issues/590
- [ ] https://github.com/GemeenteNijmegen/mijn-nijmegen/issues/596
- [ ] https://github.com/GemeenteNijmegen/mijn-nijmegen/issues/594
- [ ] https://github.com/GemeenteNijmegen/mijn-nijmegen/issues/660
- [ ] https://github.com/GemeenteNijmegen/mijn-nijmegen/issues/661
```
