### ISSUE TITLE
Header ontwerpen

### ISSUE THREAD

**Issue by joostvanderborg** [GemeenteNijmegen/mijn-nijmegen#588]
Nieuwe header in huisstijl van gemeente Nijmegen (wit, lettertype, etc.) met:
- logo
- naam van ingelogde gebruiker
- escape naar Nijmegen.nl
- zoekfunctie wenselijk (zoekt hij alleen binnen pagina's of ook binnen gegevens?)
- uitlogmogelijkheid
```[tasklist]
### Tasks
- [x] Ontwerpen in Figma
- [x] Ontwerp overleg met contentmanager
- [x] Overdragen aan front-end developer
- [x] Ontwerp als iemand lange naam heeft
```
