### ISSUE TITLE
Sidenavigatie ontwerpen

### ISSUE THREAD

**Issue by MariannevanLierop** [GemeenteNijmegen/mijn-nijmegen#596]
Menu met icons aan linkerkant (ipv top header menu items)
```[tasklist]
### Tasks
- [x] Ontwerpen in figma
- [x] Overdragen aan front-end developer
- [x] Ontwerpen drop down pagina's in sidenav?
```
