### ISSUE TITLE
Mijn zaken downloadoptie ontwerpen

### ISSUE THREAD

**Issue by MariannevanLierop** [GemeenteNijmegen/mijn-nijmegen#598]
Inwoner kan PDF + form.io formulier + bijlages van zaak downloaden
```[tasklist]
### Tasks
- [x] Ontwerpen in figma
- [x] Ontwerp overleg met contentmanager
- [x] Overdragen aan front-end developer
```

**Comment by vladimirdacosta** [comment]
@MariannevanLierop Dit was al ontworpen in het vorige ontwerp. Wat moet hier nu anders aan zijn?

**Comment by MariannevanLierop** [comment]
Welk vorige ontwerp? Prima als het al ontworpen is! Dan vink maar af en draag maar over aan developer.

**Comment by vladimirdacosta** [comment]
@MariannevanLierop volgende week aan Wendy presenteren, als ze akkoord geeft draag ik over aan dev.
