### ISSUE TITLE
Mijn zaken overzichtspagina ontwerpen

### ISSUE THREAD

**Issue by MariannevanLierop** [GemeenteNijmegen/mijn-nijmegen#601]
Inwoner ziet overzicht van actieve en afgesloten aanvragen/evenementen/vergunningen van afgelopen jaar (vooralsnog alleen vanuit systeem VIP)
```[tasklist]
### Tasks
- [x] Ontwerpen in figma
- [x] Ontwerp overleg met contentmanager
- [x] Overdragen aan front-end developer
```
