### ISSUE TITLE
Mijn zaken overzichtspagina implementeren

### ISSUE THREAD

**Issue by MariannevanLierop** [GemeenteNijmegen/mijn-nijmegen#602]
Inwoner ziet overzicht van actieve en afgesloten aanvragen/evenementen/vergunningen van afgelopen jaar (vooralsnog alleen vanuit systeem VIP)

https://mijn.accp.nijmegen.nl/zaken

```[tasklist]
### Tasks
- [ ] https://github.com/GemeenteNijmegen/mijn-nijmegen/issues/685
- [ ] Vladimir geeft nog feedback
- [ ] Myriam geeft feedback
- [ ] Marianne maakt update op iNsite voor collega's als het live staat
```
