### ISSUE TITLE
Mijn zaken detailpagina ontwerpen

### ISSUE THREAD

**Issue by MariannevanLierop** [GemeenteNijmegen/mijn-nijmegen#604]
Inwoner ziet details van 1 specifieke aanvraag: status + proces + resultaat + einddatum
```[tasklist]
### Tasks
- [x] Ontwerpen in figma
- [x] Ontwerp overleg met contentmanager
- [x] Ontwerp statustekst bovenaan pagina zodat inwoner in 1 oogopslag ziet wat huidige status is: https://www.figma.com/file/MScSuv6Z23Z0LFfCWXAxdY?node-id=105:548&mode=design#595575517
- [x] Overdragen aan front-end developer
```
