### ISSUE TITLE
EPIC: Mijn Nijmegen voor bedrijf/rechtspersoon

### ISSUE THREAD

**Issue by MariannevanLierop** [GemeenteNijmegen/mijn-nijmegen#607]
Bedrijven en rechtspersonen gebruiken Mijn Nijmegen
(Open Zaak bij Woweb/VIP nodig)
```[tasklist]
### Tasks
- [ ] https://github.com/GemeenteNijmegen/mijn-nijmegen/issues/608
- [ ] https://github.com/GemeenteNijmegen/mijn-nijmegen/issues/609
- [ ] https://github.com/GemeenteNijmegen/mijn-nijmegen/issues/625
- [ ] https://github.com/GemeenteNijmegen/mijn-nijmegen/issues/626
```
