### ISSUE TITLE
Mijn bedrijfsgegevens ontwerpen

### ISSUE THREAD

**Issue by MariannevanLierop** [GemeenteNijmegen/mijn-nijmegen#608]
Mijn gegevens (binnen Mijn Nijmegen) voor bedrijven en rechtspersonen (Open Zaak bij Woweb/VIP nodig)
```[tasklist]
### Tasks
- [x] Ontwerpen in figma
- [x] Ontwerp overleg met contentmanager
- [x] Overdragen aan front-end developer
```

**Comment by MariannevanLierop** [comment]
@joostvanderborg jij gaat checken met Wendy of we deze pagina nodig hebben of dat naam rechtsboven in scherm voldoende is voor bedrijven. Of op homepage iets van welkom x.

**Comment by vladimirdacosta** [comment]
@joostvanderborg Het prototype is beschikbaar op: https://shorturl.at/kAOV5.
