### ISSUE TITLE
Homepage ontwerpen

### ISSUE THREAD

**Issue by MariannevanLierop** [GemeenteNijmegen/mijn-nijmegen#614]
Inwoner ziet overzicht van belangrijkste dingen op de homepage van Mijn Nijmegen (via logo altijd bereikbaar).

Mogelijke scenario's voor inwoners:
1. Geen zaak + geen uitkering
2. Wel zaak + geen uitkering
3. Geen zaak + wel uitkering
4. Wel zaak + wel uitkering

```[tasklist]
### Tasks
- [x] Scenario 1 ontwerpen in figma
- [x] Scenario 2 ontwerpen in figma
- [x] Scenario 3 ontwerpen in figma
- [x] Scenario 4 ontwerpen in figma
- [x] Ontwerp maken voor inwoner met >10 lopende zaken
- [x] Ontwerp maken voor Mijn taken op homepage?
- [x] Ontwerp overleg met contentmanager
- [x] Overdragen aan front-end developer
```

**Comment by MariannevanLierop** [comment]
@iamskip , dit issue is aangevuld met scenario to do's

**Comment by vladimirdacosta** [comment]
@joostvanderborg kan je een overzicht maken van de soort zaken die een inwoner kan hebben ?

**Comment by joostvanderborg** [comment]
Hoe bedoel je 't precies? Zaken kan van alles zijn, van een verhuizing tot een naamswijziging, van een uitkeringsaanvraag tot een evenementenvergunning. Het eerste systeem dat we aansluiten gaat over dingen als evenementenvergunningen, alcoholvergunningen e.d.

**Comment by vladimirdacosta** [comment]
Bedankt voor de verduidelijking.
Ik wilde begrijpen welke zaken een inwoner kan hebben en hoe vaak het voorkomt dat een inwoner daadwerkelijk 10 verschillende zaken tegelijkertijd heeft, om een ontwerp te kunnen maken waarin een inwoner 10 zaken kan hebben. Het is namelijk niet efficiënt om ontwerpen te maken voor situaties die mogelijk nooit voorkomen. Als jullie verwachten dat dit vaak voorkomt, is het inderdaad zinvol om te overwegen hoe we de pagina het beste kunnen structureren, zodat het voor de inwoners overzichtelijk blijft.

**Comment by joostvanderborg** [comment]
Ik denk dat we ook met grote aantallen rekening moeten houden, ook omdat straks ook ondernemers toegang krijgen, en die bijvoorbeeld veel meer vergunningsaanvragen kunnen doen.
