### ISSUE TITLE
Mijn uitkering ontwerpen

### ISSUE THREAD

**Issue by MariannevanLierop** [GemeenteNijmegen/mijn-nijmegen#620]
Inwoner ziet snel en duidelijk geldzaken uit participatiewet + IOAW/IOAZ
```[tasklist]
### Tasks
- [x] Titel 'Mijn uitkering' bespreken met contentmanger
- [x] Ontwerp maken zoals tabel voorstel Joost (verleden, heden en toekomst in 1 overzicht) Alle info in comment in figma: https://www.figma.com/file/MScSuv6Z23Z0LFfCWXAxdY?node-id=169:5756&mode=design#588362779
- [x] Ontwerpen secnario dat inwoner geen uitkering krijgt ( 'U ontvangt momenteel geen uitkeringen')
- [x] Ontwerpen scenario dat inwoner meer dan 1 uitkering krijgt
- [x] Ontwerp overleg met contentmanager
- [x] Overdragen aan dev
```
