### ISSUE TITLE
Mijn taken ontwerpen

### ISSUE THREAD

**Issue by MariannevanLierop** [GemeenteNijmegen/mijn-nijmegen#628]
Ambtenaar kan taak toekennen aan inwoner 
```[tasklist]
### Tasks
- [x] Ontwerpen
- [x] Ontwerp overleg met contentmanager
- [x] Overdragen
- [x] Ontwerp voor inwoner met 0 taken
- [x] Ontwerp voor inwoner met 10 taken
```

**Comment by joostvanderborg** [comment]
https://www.figma.com/file/MScSuv6Z23Z0LFfCWXAxdY/MijnNijmegen?type=design&node-id=1581%3A6129&mode=design&t=0uSmUUiASRuvNN3m-1
