### ISSUE TITLE
Notificatievoorkeuren ontwerpen

### ISSUE THREAD

**Issue by MariannevanLierop** [GemeenteNijmegen/mijn-nijmegen#634]
Inwoner kan voorkeuren (e-mail/sms) voor notificaties in profiel opslaan 
```[tasklist]
### Tasks
- [ ] Profiel ontwerpen --> Vladimir
- [ ] Voorkeuren opslaan ontwerpen --> Vladimir
- [ ] Ontwerp overleg met contentmanager --> Vladimir
- [ ] Overdragen via comp biblio project --> Marianne
```
