### ISSUE TITLE
Gebruikersonderzoek met inwoners

### ISSUE THREAD

**Issue by MariannevanLierop** [GemeenteNijmegen/mijn-nijmegen#697]
Opzet opdrachten gebruikersonderzoek: https://irvn-my.sharepoint.com/:w:/g/personal/m_van_kollenburg_nijmegen_nl/EZ7YlS0qCAxPlmhqOUWvqckBX-9pDK5lzO7eN0qixToU1Q?e=sS7H79

```[tasklist]
### Tasks
- [x] Opdrachten voorbereiden
- [x] Tests op kantoor met cliëntenraad
- [x] Testen met Team Online
- [x] Tests op straat
- [x] Feedback verzamelen
- [x] Vladimir feedback verwerken
```
