### ISSUE TITLE
Inzendingen ontwerpen

### ISSUE THREAD

**Issue by MariannevanLierop** [GemeenteNijmegen/mijn-nijmegen#749]
Tijdelijke toevoeging aan Mijn Nijmegen:
Inwoner kan ingediende aanvraag terug zien op Mijn Nijmegen. Omdat het geen koppeling heeft met de backoffice applicatie zie je verder de status niet. Het blijft dus bij alleen die inzending. Apart onderdeel binnen Mijn zaken van maken?

Verschil tussen inzendingen en zaken: https://github.com/GemeenteNijmegen/mijn-nijmegen/issues/752

```[tasklist]
### Tasks
- [x] Joost levert verschil aan tussen inzending en zaak: https://github.com/GemeenteNijmegen/mijn-nijmegen/issues/752
- [ ] Ontwerp maken in figma
- [ ] Ook ontwerp maken als inwoner geen inzendingen heeft
- [ ] Overleg met contentmanager
- [ ] Myriam --> Content comments geven in tabblad Prototype
- [ ] Content comments verwerken
- [ ] Figma overdragen aan Joost incl link
```

**Comment by MariannevanLierop** [comment]
@iamskip , ticket is gevuld!

**Comment by MariannevanLierop** [comment]
@iamskip lukt het met het ontwerp en de comments van Myriam? Had jij deze tickets al overgedragen aan Joost? :) Dan kan hij aan de slag na zijn vakantie

**Comment by vladimirdacosta** [comment]
@joostvanderborg 
De term 'Mijn Inzendingen' is intern in gebruik, maar niet bekend bij gebruikers. Het kan verwarrend zijn voor gebruikers wanneer verschillende menu-items bijna dezelfde informatie tonen. Gebruikers dienen zaken in bij de gemeente zonder kennis te hebben van de gebruikte interne terminologie en processen. Daarom is het aan te raden geen onderscheid te maken tussen 'Mijn Inzendingen' en 'Mijn Zaken'. Voor gebruikers is alles simpelweg een zaak.
