### ISSUE TITLE
Highlight status binnen Mijn zaken vragen aan NL Design System/Den Haag

### ISSUE THREAD

**Issue by MariannevanLierop** [GemeenteNijmegen/mijn-nijmegen#759]
Alle info in comment figma: https://www.figma.com/file/MScSuv6Z23Z0LFfCWXAxdY?node-id=637:1581&mode=design#595587140
```[tasklist]
### Tasks
- [x] Contact met Den Haag opnemen of wij dit highlight component kunnen gebruiken
- [x] Ontwerpen
- [ ] Testen met gebruikers (prefence testing)
- [ ] Bespreken met Myriam
- [ ] Overdragen aan developer
- [ ] Conclusies delen met NL design system community
```
