### ISSUE TITLE
EPIC: hoofdbewoner een verhuizing laten accorderen (deel C)

### ISSUE THREAD

**Issue by wvdeeckhout** [GemeenteNijmegen/mijn-nijmegen#804]
Op dit moment loopt het proces mbt een verhuizing niet goed waar een hoofdbewoner toestemming moet geven. De vraag is gesteld of we dit op een andere manier technisch  kunnen ondersteunen. 
In Zoetermeer gebruiken ze het SIM portaal. Bij het inzenden van een adreswijziging waarbij de persoon bij iemand in gaat wonen, geeft de hoofdbewoner toestemming door in Mijn Zoetermeer bij Mijn Taken en dan toestemming hoofdbewoner, de adreswijziging goed te keuren. Na toestemming wordt de adreswijziging doorgevoerd.

Publiekszaken wil deze manier van werken mogelijk maken via MijnNijmegen. 
Dit doen we door aan te sluiten op MijnTaken en deze taak via deze api op Mijn Nijmegen beschikbaar te stellen.
We wachten op de VNG, onderdeel leveranciersmanagement, om procura hierin mee te krijgen. Mocht dit lukken, dan pakken we dit op in de hackathon van 7 tm 10 oktober.

```[tasklist]
### Tasks
- [ ] https://github.com/GemeenteNijmegen/mijn-nijmegen/issues/850
- [x] technische sessie inplannen
- [ ] vervolgstappen bepalen
- [ ] https://github.com/GemeenteNijmegen/mijn-nijmegen/issues/1180
```

**Comment by joostvanderborg** [comment]
@wvdeeckhout deze kan gesloten?

**Comment by wvdeeckhout** [comment]
Toestemming hoofdbewoner vervalt in het proces, dus deze kan gesloten worden.
