### ISSUE TITLE
EPIC: VIP-taak klaarzetten op Mijn Nijmegen via MijnTaken zodat de Nijmegenaar een actie kan uitvoeren (deel A)

### ISSUE THREAD

**Issue by wvdeeckhout** [GemeenteNijmegen/mijn-nijmegen#807]
Het kan voorkomen dat een aanvraag niet compleet is of dat tijdens de behandeling van een aanvraag nog een actie door de Nijmegenaar uitgevoerd moet worden. Dit kan door een taak in Mijn Nijmegen voor de Nijmegenaar klaar te zetten. De Nijmegenaar kan dan inloggen op Mijn Nijmegen, de taak daar inzien en uitvoeren.
Er zijn verschillende soorten taken of acties mogelijk. Enkele voorbeelden:
1. uploaden van een document bij een zaak
2. informatie aanleveren door dit direct in te typen
3. betalen van een aanvraag
4. verzoek om contact op te nemen
5. ...

Wat is er al beschikbaar in acceptatie:
- Taak aanmaken in VIP voor het uitvragen van een (extra of nieuw) aan te leveren bestand 
- Objecttype en objecten api draaien in test
- Taak objecttype conform Den Haag ingeladen en toegepast
- Taken tonen in MijnNijmegen en vervolgens het bestand kunnen uploaden via formulier
- Ingevulde taak inzien en status van wijzigen in VIP

```[tasklist]
### Acties PO
- [ ] https://github.com/GemeenteNijmegen/mijn-nijmegen/issues/1173
- [ ] https://github.com/GemeenteNijmegen/mijn-nijmegen/issues/1174
- [x] nieuwste versie Taak objecttype uitvragen
```
```[tasklist]
### Technische acties
- [ ] https://github.com/GemeenteNijmegen/mijn-nijmegen/issues/1235
- [ ] https://github.com/GemeenteNijmegen/mijn-nijmegen/issues/1236
- [ ] https://github.com/GemeenteNijmegen/mijn-nijmegen/issues/1237
- [ ] https://github.com/GemeenteNijmegen/mijn-nijmegen/issues/1238
- [ ] https://github.com/GemeenteNijmegen/mijn-nijmegen/issues/1255
- [x] https://github.com/GemeenteNijmegen/mijn-nijmegen/issues/1256
- [ ] https://github.com/GemeenteNijmegen/mijn-nijmegen/issues/1172
```

**Comment by joostvanderborg** [comment]
Bericht vanuit woweb (20-8):
> Vandaag ben ik bezig geweest met het nieuwe taakpatroon in te laden op de testomgevingen. Ik heb de objecttypes-api en objects-api eerst geupdate naar de nieuwste versies (objecttypes-api:2.2.0 en objects-api:2.4.1). Daarna is het nieuwe patroon ingeladen als objecttype en heb ik je api key voor de objects api uitgebreid (je kunt dus nog dezelfde key gebruiken). Er zitten nu 2 objecttypes in, taak-oud en taak. 
>
> De testomgevingen zijn nog hetzelfde
>
> Het nieuwe taak patroon ([https://dienstverleningsplatform.gitbook.io/platform-generieke-dienstverlening-public/patronen/taken/externe-klanttaak is wel significant anders dan voorheen dus aan de kant van VIP moeten we nog wel even gaan sleutelen om een taak in het nieuwe patroon in de api te krijgen. Ik heb hier volgende week wat tijd voor ingeruimd zodat ik in ieder geval wat voorbeelden in de api kan zetten. Daarna kan jij wellicht kijken welke changes je moet doen aan de mijn Nijmegen kant. Ik zal een seintje geven als er voorbeelden in de api zitten.


In de bijlage het oude en nieuwe patroon zodat je de verschillen kunt zien.

**Comment by joostvanderborg** [comment]
Taken staan t/m acceptatie aan voor woweb (VIP). Ketentest moet nog.

**Comment by joostvanderborg** [comment]
Er is nog wat technisch 'restwerk' om dit af te krijgen. Ik wil voorstellen deze te sluiten en een losse epic voor de losse eindjes te maken. Openstaande punten hieruit even bekijken?

**Comment by wvdeeckhout** [comment]
Deze is gereed
