### ISSUE TITLE
Check content/verwijzingen vanaf nijmegen.nl

### ISSUE THREAD

**Issue by MariannevanLierop** [GemeenteNijmegen/mijn-nijmegen#811]
Checken of en hoe we verwijzen naar Mijn Nijmegen vanaf nijmegen.nl
```[tasklist]
### Tasks
- [ ] Check overlap content met nijmegen.nl
- [ ] Content op nijmegen.nl opfrissen
- [ ] Verwijzingen vanaf nijmegen.nl opfrissen
```
