### ISSUE TITLE
Verwerkingen tonen ontwerpen

### ISSUE THREAD

**Issue by MariannevanLierop** [GemeenteNijmegen/mijn-nijmegen#860]
Ontwerp maken voor het tonen van verwerkingen in Mijn Nijmegen. Voor de AVG moeten mensen inzicht hebben in persoonsgegevens en verwerkingen. Een soort verwerkingslog waarin staat wat/waarom gewijzigd is. Als wij iets wijzigen wordt er een seintje gestuurd naar dat verwerkingslog. Vooralsnog komen er alleen nog formulierinzendingen in. Wat we willen is in Mijn Nijmegen inzicht geven in dat verwerkingslog. Een soort tabel met wat wanneer gewijzigd worden is de simpelste vormgeving. Inwoner moet hier wel wat aan hebben. En binnen onderwerp of categorie kunnen meerdere wijzigingen staan. Of wat als er heel veel wijzigingen zijn, hoe moet dat visueel blijven voor inwoners? 

```[tasklist]
### Tasks
- [x] Joost zet print screens van prototype in comment hieronder
- [x] Joost zoek presentatie op van zichzelf, in comment hieronder
- [x] Myriam taggen in de card zodat ze content feedback kan geven
- [x] Meeting met Martijn van Dijk om verschil tussen handeling en actie te snappen
- [x] Uitslag juridische conflicten afwachten (en wat doen we dan?)
- [ ] Met Martijn overleggen wat nodig is om verder te kunnen --> Joost
- [ ] Ontwerp maken --> Vladimir
- [ ] Template voor test maken --> Vladimir
- [ ] Gebruikers testen
- [ ] Feedback in sprintmeeting
- [ ] Overdragen aan woweb in comp biblio bord --> Marianne
```

**Comment by joostvanderborg** [comment]
In deze presentatie (t/m slide 17 relevant) is uitleg over de opzet, en een demo-afbeelding van prototype te zien: https://irvn-my.sharepoint.com/:p:/g/personal/j_van_der_borg_nijmegen_nl/EXrLUFzUKcJIjSPrtngsdQYBPnUEG5omZQTqgWIKM0MyPQ?e=lo8thy

De tabel op deze pagina halverwege is ook nog wel te begrijpen, alle technische details zijn vanuit hier ook te vinden: https://vng-realisatie.github.io/gemma-verwerkingenlogging/quickstart

**Comment by joostvanderborg** [comment]
Van webformulieren slaan we nu op:
```
      actieNaam: `Ophalen en opslaan van persoonsgegeven tbv formulier inzending <formuliernaam>`,
      handelingNaam: `Formulier inzending <ID van inzending>`,
      verwerkingNaam: 'Verwerken gegevens voor aanvragen voor gemeentelijke producten en diensten',
```
En daarbij welke persoonsgegevens (BSN, niet ingevuld BSN maar de term BSN)

**Comment by MariannevanLierop** [comment]
@iamskip 

Samenvatting feedback stand-up 3-4-2024

- Verwerkingsactiviteit kan weg
- Verwerking kan weg
- Handeling en actie wordt uitgebreid met WAT DAN: Belangrijkste is dat inwoner inzage heeft in wie wanneer en waarom welke gegevens van mij heeft geraadpleegd. Wie kan nog niet. Dus waarom (proces/naam formulier/telefoontje) zijn welke gegevens van mij geraadpleegd en voor welke actie?
- Onder handeling en actie kunnen meerdere wijzigingen/opvragingen hangen.

Dus dit moet visueel duidelijk zijn voor inwoners want het kan groot en veel zijn. Lukt het je om dat te ontwerpen?

**Comment by MariannevanLierop** [comment]
@joostvanderborg zou jij Martijn update willen vragen over details over wat er weergegeven kan worden.

**Comment by WietekeNijmegen** [comment]
@MariannevanLierop en @iamskip We hebben net besproken of de informatie van verwerkinglogging besproken kan worden. Er zijn nog zaken onduidelijk en die kunnen we nu niet oppakken. Dit wordt dus verschoven naar een andere sprint. Nog niet duidelijk wanneer dit wel kan.
