### ISSUE TITLE
Inlogscherm ontwerpen

### ISSUE THREAD

**Issue by MariannevanLierop** [GemeenteNijmegen/mijn-nijmegen#964]
https://www.figma.com/design/MScSuv6Z23Z0LFfCWXAxdY/MijnNijmegen?node-id=1581-3879&t=3zGYkNdbkmCeTSlH-0. 

@iamskip, feedback Wendy: Op productie is Yivi alleen voor inwoners. 1 nieuwe versie maken waardoor duidelijk is dat Yivi alleen voor inwoners is. Op acceptatie is Yivi wel voor bedrijven dus huidige ontwerp is daar nog voor te gebruiken.

```[tasklist]
### Tasks
- [x] Ontwerpen
- [x] 3 categorieen veranderen zodat het begrijpelijk is --> Vladimir/Myriam
- [x] Content checken --> Myriam
- [x] Ontwerp aanpassen --> Vladimir
- [x] Marianne laten weten als ontwerp klaar is --> Marianne
- [x] Overdragen aan Joost --> Vladimir
- [x] Wendy ontwerp mailen --> Marianne
- [x] Ticket aanmaken in nijmegen.nl/comp biblio bord
- [ ] 1 versie voor productie ontwerpen (Yivi alleen voor inwoners) --> Vladimir
- [ ] Component maken via comp biblio project
```

**Comment by joostvanderborg** [comment]
@iamskip Button aansluitend maken op figma-ontwerp van button ihkv component library (groene rand iii)

**Comment by vladimirdacosta** [comment]
@MariannevanLierop Morgen ben ik niet aanwezig tijdens de sprintmeeting. Mijn oplossing voor het loginscherm heb ik hier uitgewerkt:
[Login scherm ontwerp](https://www.figma.com/design/MScSuv6Z23Z0LFfCWXAxdY/MijnNijmegen?node-id=2015-9998&t=NOa8lgDMdTZYCGB3-4)
